server:
  port: 9001
spring:
  application:
    name: tensquare_base
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://152.136.52.66:3306/yunqy_base?characterEncoding=utf-8
    username: root
    password: 123456
  jpa:
    database: MySQL
    show-sql: true
    generate-ddl: true
